// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg4zPXnNYPGvCxI0fy0f2f0oFJfHDG_JI',
    appId: '1:24538391923:web:31e3a2944564d877275106',
    messagingSenderId: '24538391923',
    projectId: 'limos-quizpart2',
    authDomain: 'limos-quizpart2.firebaseapp.com',
    storageBucket: 'limos-quizpart2.appspot.com',
    measurementId: 'G-FZF6Y1WBPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmGIbU-47v3Sfh2UzwPrWcwfVRffapFWc',
    appId: '1:24538391923:android:08b2563b796f0dc7275106',
    messagingSenderId: '24538391923',
    projectId: 'limos-quizpart2',
    storageBucket: 'limos-quizpart2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtDxOx7U91ZKJWd4cH7uiF24Isxof3pks',
    appId: '1:24538391923:ios:86b03d5183077db1275106',
    messagingSenderId: '24538391923',
    projectId: 'limos-quizpart2',
    storageBucket: 'limos-quizpart2.appspot.com',
    iosBundleId: 'com.example.limosquizpart2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtDxOx7U91ZKJWd4cH7uiF24Isxof3pks',
    appId: '1:24538391923:ios:d7da4cd14eeed4f6275106',
    messagingSenderId: '24538391923',
    projectId: 'limos-quizpart2',
    storageBucket: 'limos-quizpart2.appspot.com',
    iosBundleId: 'com.example.limosquizpart2.RunnerTests',
  );
}
